basePath: /
consumes:
    - application/json
definitions:
    Product:
        description: Product defines the structure for an API product
        x-go-package: github.com/goocarry/mstemplate/data
info:
    description: '# Documentation for Product API'
    title: classification of Product API
paths:
    /products:
        get:
            description: Returns a list of products
            operationId: listProducts
            responses:
                "200":
                    $ref: '#/responses/productsResponse'
    /products/{id}:
        delete:
            description: Deletes product from productList
            operationId: deleteProduct
            parameters:
                - description: The id of the product to delete from the database
                  format: int64
                  in: path
                  name: id
                  required: true
                  type: integer
                  x-go-name: ID
            responses:
                "201":
                    $ref: '#/responses/noContent'
produces:
    - application/json
responses:
    noContent:
        description: ""
    productsResponse:
        description: A list of products returns in the response
        schema:
            items: {}
            type: array
schemes:
    - http
swagger: "2.0"
